CREATE TABLE IF NOT EXISTS authors (
    id     SERIAL PRIMARY KEY NOT NULL,
    author VARCHAR(50)        NOT NULL
);

INSERT INTO authors(author) VALUES
('Bob Marley'),
('Eleanor Roosevelt'),
('Mark Twain'), 
('Pablo Picasso'), 
('Dolly Parton'), 
('Friedrich Nietzsche'),
('Winston Churchill'),
('Groucho Marx'),
('Abraham Lincoln'),
('Isaac Asimov'),
('Victor Hugo'),
('George Carlin'),
('Orson Welles');

CREATE TABLE IF NOT EXISTS categories (
    id       SERIAL PRIMARY KEY NOT NULL,
    category VARCHAR(20)        NOT NULL
);

INSERT INTO categories (category) VALUES
('Wisdom'),
('Music'), 
('Art'),
('Food'), 
('Pets'),
('Funny'),
('Science');

CREATE TABLE IF NOT EXISTS quotes (
    id          SERIAL PRIMARY KEY NOT NULL,
    quote       TEXT               NOT NULL,
    author_id   INT                NOT NULL,
    category_id INT                NOT NULL,
    CONSTRAINT fk_author_id FOREIGN KEY (author_id) REFERENCES authors(id),
    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES categories(id)
);

INSERT INTO quotes (quote, author_id, category_id) VALUES
('Don''t gain the world and lose your soul; wisdom is better than silver or gold.',
    (SELECT id FROM authors WHERE author = 'Bob Marley'),
    (SELECT id FROM categories WHERE category = 'Wisdom')),
('Great minds discuss ideas; average minds discuss events; small minds discuss people.',
    (SELECT id FROM authors WHERE author = 'Eleanor Roosevelt'),
    (SELECT id FROM categories WHERE category = 'Wisdom')),
('The only way to keep your health is to eat what you don''t want, drink what you don''t like, and do what you''d rather not.',
    (SELECT id FROM authors WHERE author = 'Mark Twain'),
    (SELECT id FROM categories WHERE category = 'Food')),
('Every single diet I ever fell off of was because of potatoes and gravy of some sort.', 
    (SELECT id FROM authors WHERE author = 'Dolly Parton'),
    (SELECT id FROM categories WHERE category = 'Food')),
('The purpose of art is washing the dust of daily life off our souls.',
    (SELECT id FROM authors WHERE author = 'Pablo Picasso'),
    (SELECT id FROM categories WHERE category = 'Art')),
('Without music, life would be a mistake.', 
    (SELECT id FROM authors WHERE author = 'Friedrich Nietzsche'),
    (SELECT id FROM categories WHERE category = 'Music')),
('I am fond of pigs. Dogs look up to us. Cats look down on us. Pigs treat us as equals.',
    (SELECT id FROM authors WHERE author = 'Winston Churchill'),
    (SELECT id FROM categories WHERE category = 'Pets')),
('Outside of a dog, a book is a man''s best friend. Inside of a dog it''s too dark to read.',
    (SELECT id FROM authors WHERE author = 'Groucho Marx'),
    (SELECT id FROM categories WHERE category = 'Pets')),
('No matter how much cats fight, there always seem to be plenty of kittens.',
    (SELECT id FROM authors WHERE author = 'Abraham Lincoln'),
    (SELECT id FROM categories WHERE category = 'Pets')),
('People who think they know everything are a great annoyance to those of us who do.',
    (SELECT id FROM authors WHERE author = 'Isaac Asimov'),
    (SELECT id FROM categories WHERE category = 'Wisdom')),
('I refuse to join any club that would have me as a member.',
    (SELECT id FROM authors WHERE author = 'Groucho Marx'),
    (SELECT id FROM categories WHERE category = 'Funny')),
('The essence of all beautiful art, all great art, is gratitude.',
    (SELECT id FROM authors WHERE author = 'Friedrich Nietzsche'),
    (SELECT id FROM categories WHERE category = 'Art')),
('Without tradition, art is a flock of sheep without a shepherd. Without innovation, it is a corpse.',
    (SELECT id FROM authors WHERE author = 'Winston Churchill'),
    (SELECT id FROM categories WHERE category = 'Art')),
('One good thing about music, when it hits you, you feel no pain.', 
    (SELECT id FROM authors WHERE author = 'Bob Marley'),
    (SELECT id FROM categories WHERE category = 'Music')),
('Music expresses that which cannot be said and on which it is impossible to be silent.', 
    (SELECT id FROM authors WHERE author = 'Victor Hugo'),
    (SELECT id FROM categories WHERE category = 'Music')),
('May the forces of evil become confused on the way to your house.',
    (SELECT id FROM authors WHERE author = 'George Carlin'),
    (SELECT id FROM categories WHERE category = 'Funny')),
('Don''t sweat the petty things and don''t pet the sweaty things.',
    (SELECT id FROM authors WHERE author = 'George Carlin'),
    (SELECT id FROM categories WHERE category = 'Funny')),
('What kills a skunk is the publicity it gives itself.',
    (SELECT id FROM authors WHERE author = 'Abraham Lincoln'),
    (SELECT id FROM categories WHERE category = 'Wisdom')),
('No man has a good enough memory to be a successful liar.',
    (SELECT id FROM authors WHERE author = 'Abraham Lincoln'),
    (SELECT id FROM categories WHERE category = 'Wisdom')),
('I love Velveeta cheese.',
    (SELECT id FROM authors WHERE author = 'Dolly Parton'),
    (SELECT id FROM categories WHERE category = 'Food')),
('Buy land, they''re not making it anymore.',
    (SELECT id FROM authors WHERE author = 'Mark Twain'),
    (SELECT id FROM categories WHERE category = 'Wisdom')),
('It''s not the size of the dog in the fight; it''s the size of the fight in the dog.',
    (SELECT id FROM authors WHERE author = 'Mark Twain'),
    (SELECT id FROM categories WHERE category = 'Pets')),
('My doctor told me to stop having intimate dinners for four. Unless there are three other people.',
    (SELECT id FROM authors WHERE author = 'Orson Welles'),
    (SELECT id FROM categories WHERE category = 'Food')),
('The true delight is in the finding out rather than in the knowing.',
    (SELECT id FROM authors WHERE author = 'Isaac Asimov'),
    (SELECT id FROM categories WHERE category = 'Science')),
('There is a single light of science, and to brighten it anywhere is to brighten it everywhere.',
    (SELECT id FROM authors WHERE author = 'Isaac Asimov'),
    (SELECT id FROM categories WHERE category = 'Science')),
('He who opens a school door, closes a prison.',
    (SELECT id FROM authors WHERE author = 'Victor Hugo'),
    (SELECT id FROM categories WHERE category = 'Wisdom')),
('I passionately hate the idea of being with it; I think an artist has always to be out of step with his time.',
    (SELECT id FROM authors WHERE author = 'Orson Welles'),
    (SELECT id FROM categories WHERE category = 'Art')),
('Frisbeetarianism is the belief that when you die, your soul goes up on the roof and gets stuck.',
    (SELECT id FROM authors WHERE author = 'George Carlin'),
    (SELECT id FROM categories WHERE category = 'Funny')),
('Electricity is really just organized lightning.',
    (SELECT id FROM authors WHERE author = 'George Carlin'),
    (SELECT id FROM categories WHERE category = 'Science'));